version: "2.1"
services:
  tasks-ms:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      tasks-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I tasks-ms:3003/tasks-ms/resources/tasks/ --fail"
      interval: 20s
      retries: 10
  tasks-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tasks-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
